### ISSUE TITLE
Not support with permission_handler: ^9.1.0

### ISSUE THREAD

**Issue by saelco** [parmeetmaster/file_support#1]
I got error with new permission_handler:

Because file_support 1.0.3+6 depends on permission_handler ^8.3.0 and no versions of file_support match >1.0.3+6 <2.0.0, file_support ^1.0.3+6 requires permission_handler ^8.3.0.
So, because myproject depends on both permission_handler ^9.1.0 and file_support ^1.0.3+6, version solving failed.

Any plan to support permission_handler: ^9.1.0?

**Comment by parmeetmaster** [comment]
Sorry for delay.

okay please share your flutter version so i can test and update solution for you

**Comment by saelco** [comment]
Channel stable, 3.0.3,
btw, current permission_handler version is 10.0.0

**Comment by parmeetmaster** [comment]
Hey i update channel and push new code check now new version
