### ISSUE TITLE
getFileSize issue for Pdf

### ISSUE THREAD

**Issue by JayMoliya33** [parmeetmaster/file_support#2]
File size is always returning 0 for PDF extension by calling getFileSize().

**Comment by parmeetmaster** [comment]
okay i check and share you solution in next 24 hours

**Comment by parmeetmaster** [comment]
Hey Jay,

I check with multiple pdf it's already working fine. Please check my example that is given in the project it contains a complete solution to do.

Screenshot 1 :
![image](https://user-images.githubusercontent.com/42370506/178780305-f92540d7-6a3e-41cd-9947-b8942b12d33f.png)

Screenshot 2: 
![image](https://user-images.githubusercontent.com/42370506/178779964-4dd38949-fe05-4547-be84-dde4ac4f28df.png)
